// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMXQqqkMfk-VGdhF21fxsKJU2RqCwkuD8',
    appId: '1:231869554957:web:13e3c0e3dd21c28f6fd044',
    messagingSenderId: '231869554957',
    projectId: 'fruit-hub-b326e',
    authDomain: 'fruit-hub-b326e.firebaseapp.com',
    storageBucket: 'fruit-hub-b326e.appspot.com',
    measurementId: 'G-LGVLB68EF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0CRbqo4vA1Mk3oWSgYvM9dyl5bLKzte4',
    appId: '1:231869554957:android:e30162671335a46d6fd044',
    messagingSenderId: '231869554957',
    projectId: 'fruit-hub-b326e',
    storageBucket: 'fruit-hub-b326e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPmPoh8RtkmU66TbyAQHS6p9bSteX5MM',
    appId: '1:231869554957:ios:15afd2a3519447b36fd044',
    messagingSenderId: '231869554957',
    projectId: 'fruit-hub-b326e',
    storageBucket: 'fruit-hub-b326e.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcPmPoh8RtkmU66TbyAQHS6p9bSteX5MM',
    appId: '1:231869554957:ios:15afd2a3519447b36fd044',
    messagingSenderId: '231869554957',
    projectId: 'fruit-hub-b326e',
    storageBucket: 'fruit-hub-b326e.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMXQqqkMfk-VGdhF21fxsKJU2RqCwkuD8',
    appId: '1:231869554957:web:aa1344b0724fc7d96fd044',
    messagingSenderId: '231869554957',
    projectId: 'fruit-hub-b326e',
    authDomain: 'fruit-hub-b326e.firebaseapp.com',
    storageBucket: 'fruit-hub-b326e.appspot.com',
    measurementId: 'G-LBYRVEC0FT',
  );
}
